<?php
$escape = $this->plugin('escapeHtml');
$plugins = $this->getHelperPluginManager();
$hasNext = $plugins->has('previousResource');

$this->htmlElement('body')->appendAttribute('class', 'item resource show');

$embedMediaSetting = $this->siteSetting('item_media_embed');
$itemMedia = $item->media();
if ($embedMediaSetting == 1) {
    $sortedMedia = $this->SortMedia($itemMedia);
    $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
    $iiifMedia = (isset($sortedMedia['iiifMedia'])) ? $sortedMedia['iiifMedia'] : null;
    $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
} else {
    $otherMedia = $itemMedia;
}

$values = $item->values();
$eventManager = $item->getEventManager();
$args = $eventManager->prepareArgs(["values" => $values]);
$eventManager->trigger("rep.resource.display_values", $item, $args);
$values = $args["values"];

$propertiesGroup = $this->themeSetting("properties_group_items");
$propertiesGroup = json_decode($propertiesGroup);
if($propertiesGroup == null)
    $propertiesGroup = [];

$withGroup = [];
foreach($propertiesGroup as $group){
    $group->values = ["values" => []];
    foreach($group->terms as $term){
        if(isset($values[$term])){
            $group->values["values"][$term] = $values[$term];
            $withGroup[] = $term;
        }
    }
}
foreach($withGroup as $term){
    unset($values[$term]);
}

$mediaCaption = $this->themeSetting('media_caption');
if($mediaCaption == null)
    $mediaCaption = "none";
?>

<div class="main-block">
    <?php if ($hasNext): ?>
        <div class="previous-next-items">
            <?php if ($previous = $this->previousResource($resource)): ?>
                <?= $previous->link("Contenu précédent", null, ['class' => 'previous-item']) ?>
            <?php endif; ?>
            <?php if ($next = $this->nextResource($resource)): ?>
                <?= $next->link("Contenu suivant", null, ['class' => 'next-item']) ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?= $this->pageTitle($item->displayTitle(), 2); ?>
    <?php $this->trigger('view.show.before'); ?>

    <div class="properties">
        <?= $this->partial("common/resource-values", ["values" => $values]) ?>
    </div>

    <?php foreach($propertiesGroup as $group): ?>
        <?php if($group->position == "main" && count($group->terms) > 0): ?>
            <?= $this->partial("common/properties-group", ["group" => $group]) ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $item->displaySubjectValues($page, 25, $property);
    ?>
    <?php if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?php echo $this->translate('Linked resources'); ?></h3>
        <?php echo $subjectValues; ?>
    </div>
    <?php endif; ?>

    <?php if ($hasNext): ?>
        <div class="previous-next-items">
            <?php if ($previous = $this->previousResource($resource)): ?>
                <?= $previous->link("Contenu précédent", null, ['class' => 'previous-item']) ?>
            <?php endif; ?>
            <?php if ($next = $this->nextResource($resource)): ?>
                <?= $next->link("Contenu suivant", null, ['class' => 'next-item']) ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

</div>

<div class="secondary-block">
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
        <div class="properties" id="itemSets">
            <div class="property">
                <?php if(count($itemSets) > 1): ?>
                    <h4><?= $this->translate('Item sets'); ?></h4>
                <?php else: ?>
                    <h4><?= $this->translate('Item set'); ?></h4>
                <?php endif; ?>
                <div class="values">
                    <?php foreach ($item->itemSets() as $itemSet): ?>
                        <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php foreach($propertiesGroup as $group): ?>
        <?php if($group->position == "secondary-start" && count($group->terms) > 0): ?>
            <?= $this->partial("common/properties-group", ["group" => $group]) ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($lightMedia)): ?>
        <?= $this->LightGalleryOutput($lightMedia); ?>
    <?php endif; ?>

    <?php if (isset($otherMedia) && (count($otherMedia) > 0)): ?>
        <div id="other-media" class="property">
            <h4><?php echo $this->translate('Other Media'); ?></h4>
            <div class="values">
                <?php foreach($otherMedia as $media): ?>
                    <div class="value">
                        <?php echo $media->linkPretty(); ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if (isset($iiifMedia) && (count($iiifMedia) > 0)): ?>
        <div id="iiif-media" class="property">
            <div class="values">
                <?php foreach($iiifMedia as $media): ?>
                    <div class="value">
                        <a href="<?= $item->siteUrl()."/mirador"; ?>" target="_blank">
                            <div class="iiif-thumbnail">
                                <img src="<?= $media->thumbnailUrl('large') ?>"/>
                            </div>
                            <?php if($mediaCaption != "none"): ?>
                                <div class="iiif-title">
                                    <?php if($mediaCaption == "title"): ?>
                                        <?= $media->displayTitle() ?>
                                    <?php elseif($mediaCaption == "description"): ?>
                                        <?= $media->displayDescription() ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="mapping">
        <?= $this->partial('mapping/index/show'); ?>
        <?php foreach($propertiesGroup as $group): ?>
            <?php if($group->position == "mapping" && count($group->terms) > 0): ?>
                <?= $this->partial("common/properties-group", ["group" => $group]) ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>

    <?php foreach($propertiesGroup as $group): ?>
        <?php if($group->position == "secondary-end" && count($group->terms) > 0): ?>
            <?= $this->partial("common/properties-group", ["group" => $group]) ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <?= $this->partial("omeka/site/item/citation", ["item" => $item, "site" => $site]) ?>
</div>

<?= $item->embeddedJsonLd() ?>
