<?php
$escape = $this->plugin('escapeHtml');
$plugins = $this->getHelperPluginManager();
$hasNext = $plugins->has('previousResource');

$this->htmlElement('body')->appendAttribute('class', 'item resource show');

$embedMediaSetting = $this->siteSetting('item_media_embed');
$itemMedia = $item->media();
if ($embedMediaSetting == 1) {
    $sortedMedia = $this->SortMedia($itemMedia);
    $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
    $iiifMedia = (isset($sortedMedia['iiifMedia'])) ? $sortedMedia['iiifMedia'] : null;
    $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
} else {
    $otherMedia = $itemMedia;
}

$values = $item->values();
$eventManager = $item->getEventManager();
$args = $eventManager->prepareArgs(["values" => $values]);
$eventManager->trigger("rep.resource.display_values", $item, $args);
$values = $args["values"];

$propertiesBlock = $this->themeSetting("properties_block_items");
$propertiesBlock = json_decode($propertiesBlock);
if($propertiesBlock == null)
    $propertiesBlock = [];

foreach($propertiesBlock as $block){
    $block->values = ["values" => []];
    foreach($block->terms as $term){
        if(isset($values[$term])){
            $block->values["values"][$term] = $values[$term];
            unset($values[$term]);
        }
    }
}

$nakalaProperties = $this->themeSetting("nakala_properties");
if($nakalaProperties == null)
    $nakalaProperties = [];

$mediaCaption = $this->themeSetting('media_caption');
if($mediaCaption == null)
    $mediaCaption = "none";
?>

<div class="main-block">
    <?php if ($hasNext): ?>
        <div class="previous-next-items">
            <?php if ($previous = $this->previousResource($resource)): ?>
                <?= $previous->link("Contenu précédent", null, ['class' => 'previous-item']) ?>
            <?php endif; ?>
            <?php if ($next = $this->nextResource($resource)): ?>
                <?= $next->link("Contenu suivant", null, ['class' => 'next-item']) ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?= $this->pageTitle($item->displayTitle(), 2); ?>
    <?php $this->trigger('view.show.before'); ?>

    <div class="properties">
        <?= $this->partial("common/resource-values", ["values" => $values]) ?>
    </div>

    <?php foreach($propertiesBlock as $block): ?>
        <?php if($block->position == "main" && count($block->terms) > 0): ?>
            <?php
                $class = ["properties"];
                if($block->foldable){
                    $class[] = "foldable";
                    if($block->open)
                        $class[] = "open";
                }
                $class[] = $block->class;
            ?>
            <div class="<?= implode(" ", $class) ?>">
                <?php if($block->title): ?>
                    <h3><?= $block->title ?></h3>
                <?php endif; ?>
                <?= $this->partial("common/resource-values", $block->values) ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $item->displaySubjectValues($page, 25, $property);
    ?>
    <?php if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?php echo $this->translate('Linked resources'); ?></h3>
        <?php echo $subjectValues; ?>
    </div>
    <?php endif; ?>

    <?php if ($hasNext): ?>
        <div class="previous-next-items">
            <?php if ($previous = $this->previousResource($resource)): ?>
                <?= $previous->link("Contenu précédent", null, ['class' => 'previous-item']) ?>
            <?php endif; ?>
            <?php if ($next = $this->nextResource($resource)): ?>
                <?= $next->link("Contenu suivant", null, ['class' => 'next-item']) ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

</div>

<div class="secondary-block">
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
        <div class="properties" id="itemSets">
            <div class="property">
                <?php if(count($itemSets) > 1): ?>
                    <h4><?= $this->translate('Item sets'); ?></h4>
                <?php else: ?>
                    <h4><?= $this->translate('Item set'); ?></h4>
                <?php endif; ?>
                <div class="values">
                    <?php foreach ($item->itemSets() as $itemSet): ?>
                        <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php foreach($propertiesBlock as $block): ?>
        <?php if($block->position == "secondary-start" && count($block->terms) > 0): ?>
            <?php
                $class = ["properties"];
                if($block->foldable){
                    $class[] = "foldable";
                    if($block->open)
                        $class[] = "open";
                }
                $class[] = $block->class;
            ?>
            <div class="<?= implode(" ", $class) ?>">
                <?php if($block->title): ?>
                    <h3><?= $block->title ?></h3>
                <?php endif; ?>
                <?= $this->partial("common/resource-values", $block->values) ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($lightMedia)): ?>
        <?= $this->LightGalleryOutput($lightMedia); ?>
    <?php endif; ?>

    <?php if (isset($otherMedia) && (count($otherMedia) > 0)): ?>
        <div id="other-media" class="property">
            <h4><?php echo $this->translate('Other Media'); ?></h4>
            <div class="values">
                <?php foreach($otherMedia as $media): ?>
                    <div class="value">
                        <?php echo $media->linkPretty(); ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if (isset($iiifMedia) && (count($iiifMedia) > 0)): ?>
        <div id="iiif-media" class="property">
            <div class="values">
                <?php foreach($iiifMedia as $media): ?>
                    <div class="value">
                        <a href="<?= $item->siteUrl()."/mirador"; ?>" target="_blank">
                            <div class="iiif-thumbnail">
                                <img src="<?= $media->thumbnailUrl('large') ?>"/>
                            </div>
                            <?php if($mediaCaption != "none"): ?>
                                <div class="iiif-title">
                                    <?php if($mediaCaption == "title"): ?>
                                        <?= $media->displayTitle() ?>
                                    <?php elseif($mediaCaption == "description"): ?>
                                        <?= $media->displayDescription() ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if (count($nakalaProperties) > 0): ?>
        <div id="iframes" class="property">
            <div class="values">
                <?php foreach($nakalaProperties as $term):
                    $valuesNakala = $item->value($term, ["all" => true]);
                ?>
                    <?php if(count($values) > 0): ?>
                        <?php foreach($valuesNakala as $value):
                            $src = $value;
                            if($value->type() == "uri")
                                $src = $value->uri();
                        ?>
                            <div class="value">
                                <iframe src="<?= $src ?>" allow="fullscreen"></iframe>
                                <?php if(strpos($src, "https://api.nakala.fr/") !== false): ?>
                                    <?= $this->citationNakala($src) ?>
                                <?php endif; ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <?= $this->partial('mapping/index/show'); ?>

    <?php foreach($propertiesBlock as $block): ?>
        <?php if($block->position == "secondary-end" && count($block->terms) > 0): ?>
            <?php
                $class = ["properties"];
                if($block->foldable){
                    $class[] = "foldable";
                    if($block->open)
                        $class[] = "open";
                }
                $class[] = $block->class;
            ?>
            <div class="<?= implode(" ", $class) ?>">
                <?php if($block->title): ?>
                    <h3><?= $block->title ?></h3>
                <?php endif; ?>
                <?= $this->partial("common/resource-values", $block->values) ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <?= $this->partial("omeka/site/item/citation", ["item" => $item, "site" => $site]) ?>
</div>

<?= $item->embeddedJsonLd() ?>
