<?php $escape = $this->plugin('escapeHtml'); ?>

<div class="assets <?php echo $escape($className); ?> <?php echo $escape($alignment); ?>">
	<?php if(strpos($className, "carousel") !== false): ?>
		<div class="carousel-inner">
	<?php endif; ?>
	<?php foreach ($attachments as $attachment): ?>
		<?php
			$asset = $attachment['asset'];
			$class = ["asset"];
			if(strpos($className, "carousel") !== false)
				$class[] = "carousel-item";
		?>
		<div class="<?= implode(" ", $class) ?>">
			<?php $assetImage = ($asset) ? $this->thumbnail($asset, 'square', ["title" => $attachment['caption']]) : ''; ?>
			<?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
			<?php if($page): ?>
				<?php $page = $attachment['page']; ?>
				<a href="<?php echo $escape($page->siteUrl()); ?>">
					<?php echo $assetImage; ?>
					<?php $altLinkTitle = ($attachment['alt_link_title'] !== '') ? $escape($attachment['alt_link_title']) : false; ?>
					<span class="link-title"><?php echo ($altLinkTitle) ? $altLinkTitle : $escape($page->title()); ?></span>
				</a>
			<?php else: ?>
				<?php echo $assetImage; ?>
			<?php endif; ?>
			<?php if ($attachment['caption'] !== ''): ?>
				<div class="caption"><?php echo $escape($attachment['caption']); ?></div>
			<?php endif; ?>
		</div>
	<?php endforeach; ?>
	<?php if(strpos($className, "carousel") !== false): ?>
		</div>
		<div class="carousel-controls">
			<span class="prev"></span>
			<span class="next"></span>
		</div>
		<div class="carousel-indicators"></div>
	<?php endif; ?>
</div>
