<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic');
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/custom.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/resource.css'));
$this->headScript()->prependFile($this->assetUrl('js/centerrow.js'));
$this->headScript()->prependFile($this->assetUrl('js/custom.js'));
$this->headScript()->prependFile($this->assetUrl('js/qrcode.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/jquery-accessibleMegaMenu.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link rel="icon" type="image/png" href="<?= $this->assetUrl('img/icons/favicon.png') ?>">
    </head>
    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <div id="wrap">
            <header>
                <a href="<?php echo $site->url(); ?>" class="site-title">
                    <?php if ($this->themeSetting('logo')): ?>
                        <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                    <?php else: ?>
                        <?php echo $escape($siteTitle); ?>
                    <?php endif; ?>
                </a>
                <?= $this->partial('common/search-form'); ?>

                <a href="/admin" class="admin" target="_blank">
                    <i class="fas fa-user-circle"></i>
                </a>
                <div id="share">
                    <i class="fas fa-qrcode"></i>
                    <div>
                        <h4>Partager cette page</h4>
                        <div id="qrcode"></div>
                        <span>Copier le lien <i class="fas fa-copy"></i></span>
                    </div>
                </div>

                <?php echo $site->publicNav()->menu()->setPartial('common/accessible-mega-menu.phtml')->renderPartial(); ?>
            </header>

            <?= $this->partial('common/banner'); ?>
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>

            <footer>
                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>
            </footer>

            <i id="btn-top" class="fas fa-chevron-up" title="Retour en haut"></i>
        </div>
        <script type="text/javascript">
        jQuery(document).ready(function () {
            CenterRow.mobileMenu();
            CenterRow.megaMenu();
        });
        </script>
    </body>
</html>
